### ISSUE TITLE
Default Hydra version to latest release

### ISSUE THREAD

**Issue by dotta** [triplequote/intellij-scala#18]
When the user is configuring a project to use Hydra, the displayed default Hydra version we show him should be the latest released Hydra (it's currently 0.9.5, but it should be 0.9.6)

**Comment by maris123** [comment]
For me it works. Maybe it's 0.9.5 for you because you already configured that project to use 0.9.5 before 0.9.6 was released. Maybe if you try with a new project or delete the hydra.xml .

**Comment by dotta** [comment]
I'm importing a new project in IntelliJ and that's what I'm seeing. Have you also tried to import a project or did you create a new one?

**Comment by maris123** [comment]
You are right. It shows 0.9.5.  I'll fix it.
