### ISSUE TITLE
Support our Maven plugin in the ScalaMavenImporter

### ISSUE THREAD

**Issue by dragos** [triplequote/intellij-scala#20]
Currently the importer is checking for the original groupID, so it breaks for ours. But it's trivial to add another string in the checker.

**Comment by dotta** [comment]
@maris123 grep for `net.alchim31.maven` in the sources (it's the groupId for the scala-maven-plugin) and make sure to add `com.triplequote.maven` (our groupId) to the checker mentioned by @dragos in the description. That should be all it takes to fix this ticket.
