### ISSUE TITLE
Check if Username and Password are correct

### ISSUE THREAD

**Issue by maris123** [triplequote/intellij-scala#23]
There must be a mechanism that checks if the username and password are correct before the user can download the artifacts. 
If the username and password are not correct or maybe the repository is not correct   the download button will be disabled and there will be some tool tip or hint in the UI that lets the user know there is a problem with the username, password or the repo.

**Comment by dragos** [comment]
This is nice, but I don't think it's easy to do properly, nor very useful. I think that the moment the user hits download he'll get the error. For example, what if the network is down, you disable the button, and then the network comes back (user works on the Caltrain on the way to his Google office in San Francisco) 😛 I think we'd open Pandora's box.

**Comment by dotta** [comment]
I agree we have to be careful, but I also feel it's important for the user to know if the failure is due to bad credentials, connection problem, or missing artifacts. I don't think we should enable/disable the Download button as that can definitely lead to problems, but what I'd like is an informative message when the user clicks "Download" and an error occurs.

**Comment by dragos** [comment]
We should do what IntelliJ does for HTTP proxies: a different button, 'Check Connection'.

**Comment by dotta** [comment]
I'd name it "Check credentials"

-- Mirco

**Comment by dragos** [comment]
On Tue, 14 Nov 2017 at 12:24, Mirco Dotta <notifications@github.com> wrote:

> I'd name it "Check credentials"


I would name it exactly as they do in the HTTP proxy panel. Also, bad
credentials is just one reason why the connection might fail (bad url, no
network connectivity, bad SSL certificate, etc)

**Comment by dotta** [comment]
Alright! Makes sense

-- Mirco

**Comment by dotta** [comment]
This was fixed in https://github.com/triplequote/intellij-scala/pull/33
